apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mysql-pass
  data:
  - secretKey: password
    remoteRef:
      key: secret/sec
      property: password
